version: "3.1"

services:
  odoo:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8069:8069
    command: sleep infinity

  db:
    image: postgres:15
    restart: always
    ports:
      - 5432:5432
    volumes:  # persist postgres data by putting it in a workspace
      - /workspaces/meta-spaces/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres